feat: add dark mode
pantharshit00/prisma-docs-generator pull request #76
Opened 2024-03-14 22:07 UTC by sametpalitci

dark
<img width="1229" alt="dark" src="https://github.com/pantharshit00/prisma-docs-generator/assets/25365040/bb590a99-5e2b-4c5e-8905-49e33b3a82b8">
light
<img width="1258" alt="light" src="https://github.com/pantharshit00/prisma-docs-generator/assets/25365040/f36de482-4434-45ce-85db-82be9f477000">

2024-03-17 15:07 UTC, pantharshit00 commented on src/generator/apitypes.ts
> +            <h3 class="mb-2 text-2xl font-normal" id="input-types dark:text-white">Input Types</h3>
Please do the same for output types on line 94. Right now it is of wrong color in dark mode

2024-03-17 15:12 UTC, pantharshit00 commented on src/printer/index.ts
> +        class="sticky top-0 w-1/5 flex-shrink-0 h-screen p-4 px-6 overflow-auto bg-white dark:bg-black mac-h-screen"
I would like to have same bg color for sidebar and content so match them to gray-800

2024-03-17 15:15 UTC, pantharshit00 requested changes
Thanks for the work! I have requested a few small changes then it should be good.

Also, please update the snapshots once after you have made the changes using `npm run test -- -u`. Right now CI is failing because of that. 

Finally you can also maybe look into the code block sections and update those with dark theme using something like https://github.com/antfu/prism-theme-vars. That would be the final touch. You can also do a separate PR for that if you don't have enough time.

2024-03-17 17:32 UTC, sametpalitci commented
I've made the requested changes and updated the snapshot. I'm considering maybe making the Prism theme in another pull request at a later time. 

Thank you.

2024-03-20 09:15 UTC, pantharshit00 approved these changes

2024-03-20 09:15 UTC, pantharshit00 approved these changes

2024-03-20 09:16 UTC, merged